[package]
name = "katch2"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]

[[bin]]
name = "nksynth"

[dependencies]
rand = "0.10.0"
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
z3 = "0.20.0"
petgraph = "0.8.3"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "synthesis"
harness = false
